---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  labels:
    app: keycloak-postgresql
type: Opaque
stringData:
  postgres-password: ${KEYCLOAK_DB_PASSWORD}
  password: ${KEYCLOAK_DB_PASSWORD}
  replication-password: ${KEYCLOAK_DB_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  labels:
    app: keycloak-postgresql
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: keycloak-postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgresql
  labels:
    app: keycloak-postgresql
spec:
  serviceName: keycloak-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel9/postgresql-15:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              value: keycloak
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: password
            - name: POSTGRESQL_DATABASE
              value: keycloak
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U keycloak -d keycloak -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U keycloak -d keycloak -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: ${KEYCLOAK_DB_STORAGE}
