apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhdh-keycloak
  labels:
    app: keycloak
spec:
  instances: ${RHDH_KEYCLOAK_REPLICAS}
  hostname:
    strict: false
  http:
    httpEnabled: true
  ingress:
    enabled: true
  additionalOptions:
    - name: hostname-strict
      value: "false"
    - name: http-enabled
      value: "true"