apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage
  labels:
    app: keycloak
spec:
  client:
    clientId: backstage
    secret: ${KEYCLOAK_CLIENT_SECRET}
    clientAuthenticatorType: client-secret
    defaultClientScopes:
    - profile
    - email
    - roles
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    publicClient: false
    redirectUris:
      - ${OAUTH2_REDIRECT_URI}
    serviceAccountsEnabled: true
    standardFlowEnabled: true
  realmSelector:
    matchLabels:
      app: keycloak
  serviceAccountClientRoles:
    realm-management:
    - query-groups
    - query-users
    - view-users
